#http.host: 0.0.0.0
network.host: 0.0.0.0

bootstrap.memory_lock: true

# Cluster settings
cluster.name: es-cluster
cluster.initial_master_nodes: es01,es02,es03

### x-pack functions
xpack.security.enabled: false
xpack.monitoring.enabled: true
xpack.graph.enabled: true
xpack.watcher.enabled: false
