version: '3.7'
services:
  es01:
    build: ./es
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02,es03
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
#      - ./es/config/jvm.options:/usr/share/elasticsearch/config/jvm.options
    ports:
      - 9201:9200
    networks:
      - esnet

  es02:
    build: ./es
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es03,es01
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
#      - ./es/config/jvm.options:/usr/share/elasticsearch/config/jvm.options
    ports:
      - 9202:9200
    networks:
      - esnet

  es03:
    build: ./es
    container_name: es03
    environment:
      - node.name=es03
      - discovery.seed_hosts=es01,es02
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata03:/usr/share/elasticsearch/data
      - ./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
#      - ./es/config/jvm.options:/usr/share/elasticsearch/config/jvm.options
    ports:
      - 9203:9200
    networks:
      - esnet

  kibana01:
    build: ./kibana
    container_name: kibana01
    links:
      - es01:elasticsearch
    ports:
      - 5601:5601
    networks:
      - esnet
#    volumes:
#      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml


volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local

networks:
  esnet:
    driver: bridge
